#' Resolve and Link All DSSAT ID Codes
#'
#' This internal wrapper orchestrates the generation and application of all
#' standardized DSSAT codes (Experiment, Field, Cultivar, Soil, Weather).
#'
#' @details
#' This function calls the individual `.resolve_...` helpers for each section
#' (MANAGEMENT, SOIL, WEATHER) if they exist in the dataset. It then
#' collects all the `code_map` attributes generated by those helpers.
#'
#' Finally, it applies *all* code maps to the *entire* dataset list (including
#' nested tables like `dataset$MANAGEMENT$FIELDS`), ensuring
#' that referential integrity is maintained (e.g., the new PEDON ID from
#' `SOIL` is correctly applied to the `ID_SOIL` column in `MANAGEMENT$FIELDS`).
#'
#' @param dataset The full dataset list (e.g., `list(MANAGEMENT=list(...), SOIL=df, ...)`).
#'
#' @return The modified dataset list with all codes resolved and linked.
#'
#' @noRd
#' 

resolve_dssat_codes <- function(dataset) {
  
  dataset_nms_fmt <- list()
  all_code_maps <- list()
  
  exp_metadata <- dataset$MANAGEMENT_CORE
  soil_data <- dataset$SOIL
  wth_data <- dataset$WEATHER
  
  # --- Process Management ---
  if (!is.null(exp_metadata)) { 
    mngt_dssat_codes <- .resolve_dssat_mngt_codes(exp_metadata)
    # Append code map
    exp_id_map <- attr(mngt_dssat_codes, "code_map") 
    all_code_maps <- c(all_code_maps, exp_id_map)
    # Format outputs
    dataset$MANAGEMENT_CORE <- mngt_dssat_codes
  }
  
  # --- Process Soil ---
  if (!is.null(soil_data)) {
    soil_dssat_codes <- .resolve_dssat_soil_codes(soil_data)
    # Append code map
    soil_id_map <- attr(soil_dssat_codes, "code_map")
    all_code_maps$ID_SOIL <- soil_id_map
    # Update input data
    dataset$SOIL <- soil_dssat_codes
  }
  
  # --- Process Weather ---
  if (!is.null(wth_data)) {
    wth_dssat_codes <- .resolve_dssat_wth_codes(wth_data)
    # Append code map
    wth_id_map <- attr(wth_dssat_codes, "code_map")
    all_code_maps$WSTA <- wth_id_map
    # Update input data
    dataset$WEATHER <- wth_dssat_codes
  }

  return(dataset)
}





#'
#'

.resolve_dssat_mngt_codes <- function(mngt_data) {

  # --- Create standard DSSAT soil profile identifiers ---
  mngt_dssat_fmt_nms <- mngt_data %>%
    # 1- FIELD code
    dplyr::mutate(ID_FIELD = if ("ID_FIELD" %in% names(.)) ID_FIELD else "NA") %>%
    dplyr::group_by(ID_FIELD) %>%
    dplyr::mutate(
      ID_FIELD_new = if (!is_valid_dssat_id(dplyr::first(ID_FIELD), "field", "dssat")) {
        # Generate one new ID per group and apply it to all rows in that group
        generate_dssat_id(
          type = "field",
          institution = dplyr::first(INSTITUTION),
          site = dplyr::first(SITE),
          sequence_no = dplyr::cur_group_id()
        )
      } else {
        dplyr::first(ID_FIELD)
      }
    ) %>%
    dplyr::ungroup() %>%
    # 2- CULTIVAR code
    dplyr::mutate(INGENO = if ("INGENO" %in% names(.)) INGENO else "NA") %>%
    dplyr::group_by(INGENO) %>%
    dplyr::mutate(
      INGENO_new = if (!is_valid_dssat_id(dplyr::first(INGENO), "cultivar", "dssat")) {
        # Generate one new ID per group and apply it to all rows in that group
        generate_dssat_id(
          type = "cultivar",
          institution = dplyr::first(INSTITUTION),
          sequence_no = dplyr::cur_group_id()
        )
      } else {
        dplyr::first(INGENO)
      }
    ) %>%
    dplyr::ungroup() %>%
    # 3- EXPERIMENT code
    dplyr::mutate(EXP_ID = if ("EXP_ID" %in% names(.)) EXP_ID else "NA") %>%
    dplyr::mutate(EXP_YEAR = if ("EXP_YEAR" %in% names(.)) EXP_YEAR else "NNNN") %>%
    group_by(INSTITUTION, SITE, EXP_YEAR) %>%
    dplyr::mutate(
      EXP_ID_new = if (!is_valid_dssat_id(dplyr::first(EXP_ID), "experiment", "dssat")) {
        # Generate one new ID per group and apply it to all rows in that group
        generate_dssat_id(
          type = "experiment",
          institution = dplyr::first(INSTITUTION),
          site = dplyr::first(SITE),
          year = dplyr::first(EXP_YEAR),
          sequence_no = dplyr::cur_group_id()
        )
      } else {
        dplyr::first(EXP_ID)
      }
    ) %>%
    dplyr::mutate(
      file_name = paste0(EXP_ID_new, ".", CR, "X")
    ) %>%
    dplyr::ungroup()
  
  # --- Format output ---
  mngt_dssat_out <- mngt_dssat_fmt_nms |>
    dplyr::mutate(
      ID_FIELD = ID_FIELD_new,
      INGENO = INGENO_new,
      EXP_ID = EXP_ID_new
    )
  
  # ID map for referential integrity checks
  mngt_dssat_code_map <- mngt_dssat_fmt_nms |>
    dplyr::select(EXP_ID, ID_FIELD, ID_FIELD_new, INGENO, INGENO_new, EXP_ID, EXP_ID_new) |>
    dplyr::distinct()
  attr(mngt_dssat_out, "code_map") <- mngt_dssat_code_map
  
  return(mngt_dssat_out)
}


#' 
#' 

.resolve_dssat_soil_codes <- function(soil_data) {
  
  # --- Create standard DSSAT soil profile identifiers ---
  soil_dssat_fmt_nms <- soil_data %>%
    dplyr::mutate(PEDON = if ("PEDON" %in% names(.)) PEDON else "NA") %>%
    dplyr::group_by(PEDON) %>%
    dplyr::mutate(
      PEDON_new = if (!is_valid_dssat_id(dplyr::first(PEDON), "soil", "dssat")) {
        # Generate one new ID per group and apply it to all rows in that group
        generate_dssat_id(
          type = "soil",
          institution = dplyr::first(INST_NAME),
          site = dplyr::first(SITE),
          year = dplyr::first(YEAR),
          sequence_no = dplyr::cur_group_id()
        )
      } else {
        dplyr::first(PEDON)
      }
    ) %>%
    dplyr::mutate(
      file_name = paste0(strict_abbreviate(INST_NAME, 2), ".SOL")
    ) %>%
    dplyr::ungroup()
  
  # --- Format output ---
  soil_dssat_out <- soil_dssat_fmt_nms |>
    dplyr::mutate(PEDON = PEDON_new)
    #dplyr::select(EXP_ID, dplyr::any_of(union(colnames(soil_data), colnames(SOIL_template))))
  
  # ID map for referential integrity checks
  attr(soil_dssat_out, "code_map") <- soil_dssat_fmt_nms |>
    dplyr::select(EXP_ID, PEDON, PEDON_new) |>
    dplyr::distinct()
  
  return(soil_dssat_out)
}


#'
#'

.resolve_dssat_wth_codes <- function(wth_data) {
  
  # --- Create standard DSSAT weather station identifiers ---
  wth_dssat_fmt_nms <- wth_data %>%
    dplyr::mutate(INSI = if ("INSI" %in% names(.)) INSI else "NA") %>%
    dplyr::group_by(INSI, YEAR) %>%
    dplyr::mutate(
      INSI_new = if (!is_valid_dssat_id(dplyr::first(INSI), "soil", "dssat")) {
        # Generate one new ID per group and apply it to all rows in that group
        generate_dssat_id(
          type = "weather_station",
          institution = dplyr::first(INSI),  #TODO IMPUTATION!
          site = dplyr::first(WST_NAME),
          year = dplyr::first(YEAR),
          sequence_no = dplyr::cur_group_id()
        )
      } else {
        dplyr::first(INSI)
      }
    ) %>%
    dplyr::mutate(
      file_name = paste0(
        INSI_new, YEAR, sprintf("%02d", dplyr::cur_group_id()), ".WTH"
      )
    ) %>%
    dplyr::ungroup()
  
  # --- Format output ---
  wth_dssat_out <- wth_dssat_fmt_nms |>
    dplyr::mutate(INSI = INSI_new)
    # TODO: CLEAR!
    # dplyr::select(
    #   file_name,
    #   EXP_ID, WST_NAME,
    #   any_of(union(colnames(wth_data), colnames(WEATHER_header_template)))
    # )
  
  # ID map for referential integrity checks
  attr(wth_dssat_out, "code_map") <- wth_dssat_fmt_nms |>
    dplyr::select(EXP_ID, INSI, INSI_new) |>
    dplyr::distinct()
  
  return(wth_dssat_out)
}

